# Generated by Django 5.0.6 on 2024-06-16 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('page_count', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
